version: '3'

services:
  app:
    image: fernandocker21/api-faculdade
    container_name: api-faculdade
    restart: always
    environment:
      - RDS_HOST=db
      - RDS_DATABASE=faculdade
      - RDS_PORT=5432
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=postgres
    ports:
      - '3000:3000'
    command: ["sh","./start.sh"]
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
  
  db:
    image: postgres:alpine
    container_name: database-faculdade
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    tty: true
    ports:
      - '55000:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  grpc-test:
    image: gusaul/grpcox:latest
    ports:
      - 6969:6969
