version: '3'

services:
  app:
    image: fernandocker21/api-faculdade
    container_name: api-faculdade
    restart: always
    environment:
      - RDS_HOST=db
      - RDS_DATABASE=faculdade
      - RDS_PORT=5432
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=postgres
    ports:
      - '3000:3000'
    command: ["sh","./start.sh"]
    depends_on:
      - db
      - redis
    networks:
      - app-network
  
  db:
    image: postgres:alpine
    container_name: database-faculdade
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    tty: true
    ports:
      - '55000:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis
    container_name: redis-faculdade
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
